/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        /* ── Stitch export dark palette ── */
        'surface-bright': '#3a3939',
        'primary-container': '#14181c',
        'surface-container-highest': '#353535',
        'inverse-surface': '#e5e2e2',
        'surface-variant': '#353535',
        'on-tertiary-container': '#9d7c3d',
        'primary-fixed': '#e0e3e8',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#43474c',
        'on-surface-variant': '#c5c6ca',
        'tertiary-fixed-dim': '#e8c17b',
        'on-secondary-fixed': '#1c1c16',
        outline: '#8f9194',
        'surface-tint': '#c3c7cc',
        'secondary-fixed-dim': '#c9c6be',
        'on-tertiary': '#412d00',
        'surface-container-lowest': '#0e0e0e',
        'surface-container': '#201f20',
        'on-secondary-container': '#b8b5ad',
        'on-error-container': '#ffdad6',
        'on-primary': '#2d3135',
        'surface-container-low': '#1c1b1c',
        'tertiary-fixed': '#ffdea7',
        'on-primary-container': '#7e8186',
        'outline-variant': '#44474a',
        tertiary: '#e8c17b',
        'on-secondary-fixed-variant': '#484740',
        'tertiary-container': '#221500',
        'surface-dim': '#131314',
        'secondary-container': '#484740',
        'on-tertiary-fixed': '#271900',
        'on-background': '#e5e2e2',
        'on-secondary': '#31302b',
        'error-container': '#93000a',
        secondary: '#c9c6be',
        'on-surface': '#e5e2e2',
        'on-primary-fixed': '#181c20',
        'on-tertiary-fixed-variant': '#5d4207',
        primary: '#c3c7cc',
        'primary-fixed-dim': '#c3c7cc',
        background: '#131314',
        'secondary-fixed': '#e6e2d9',
        'inverse-primary': '#5b5f63',
        'inverse-on-surface': '#313030',
        surface: '#131314',
        'surface-container-high': '#2a2a2a',
        error: '#ffb4ab',
        /* ── Extra semantic tokens used across screens ── */
        'deep-jade': '#147257',
        'warm-paper': '#F7F3EA',
        'ink-navy': '#14181C',
        'rust-red': '#c0392b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        md: '16px',
        'receipt-padding': '20px',
        sm: '8px',
        unit: '4px',
        lg: '24px',
        xs: '4px',
        xl: '32px',
      },
      fontFamily: {
        'amount-sm': ['IBM Plex Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Fraunces', 'serif'],
        'amount-lg': ['IBM Plex Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Fraunces', 'serif'],
        'label-mono': ['IBM Plex Mono', 'monospace'],
        'display-lg-mobile': ['Fraunces', 'serif'],
      },
      fontSize: {
        'amount-sm': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'amount-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-mono': [
          '14px',
          {
            lineHeight: '20px',
            letterSpacing: '0.02em',
            fontWeight: '500',
          },
        ],
        'display-lg-mobile': [
          '32px',
          { lineHeight: '40px', fontWeight: '700' },
        ],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        slideInFromTop: {
          '0%': { transform: 'translateY(-16px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        celebrationBurst: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        spinSlow: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        slideInFromTop: 'slideInFromTop 0.25s ease-out forwards',
        fadeIn: 'fadeIn 0.2s ease-out forwards',
        celebrationBurst: 'celebrationBurst 0.6s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.18s ease-out forwards',
        'spin-slow': 'spinSlow 1.4s linear infinite',
      },
    },
  },
  plugins: [],
};
